name: Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Semantic Release
        run: |
          touch .env
          echo CROWDIN_TOKEN=$CROWDIN_TOKEN >> .env
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

      - name: Push changes to main branch
        run: |
          # Ensure we are on the main branch
          git checkout main

          # Push local changes to the main branch
          git push origin main

      - name: Merge changes from main into dev
        run: |
          # Switch to the dev branch
          git checkout dev

          # Merge changes from the main branch into dev
          git merge main

          # Push changes to the dev branch
          git push origin dev
